In [16]:
import pandas as pd
import numpy as np
from sklearn. naive_bayes import GaussianNB
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import train_test_split

In [17]:
df=pd.read_csv('C:\\Users\\LENOVO\\Downloads\\SalaryData_Train.csv')
df

age          workclass    education  educationno        maritalstatus  \
0       39          State-gov    Bachelors           13        Never-married   
1       50   Self-emp-not-inc    Bachelors           13   Married-civ-spouse   
2       38            Private      HS-grad            9             Divorced   
3       53            Private         11th            7   Married-civ-spouse   
4       28            Private    Bachelors           13   Married-civ-spouse   
...    ...                ...          ...          ...                  ...   
30156   27            Private   Assoc-acdm           12   Married-civ-spouse   
30157   40            Private      HS-grad            9   Married-civ-spouse   
30158   58            Private      HS-grad            9              Widowed   
30159   22            Private      HS-grad            9        Never-married   
30160   52       Self-emp-inc      HS-grad            9   Married-civ-spouse   

               occupation    relationship    race      sex  capitalgain  \
0            Adm-clerical   Not-in-family   White     Male         2174   
1         Exec-managerial         Husband   White     Male            0   
2       Handlers-cleaners   Not-in-family   White     Male            0   
3       Handlers-cleaners         Husband   Black     Male            0   
4          Prof-specialty            Wife   Black   Female            0   
...                   ...             ...     ...      ...          ...   
30156        Tech-support            Wife   White   Female            0   
30157   Machine-op-inspct         Husband   White     Male            0   
30158        Adm-clerical       Unmarried   White   Female            0   
30159        Adm-clerical       Own-child   White     Male            0   
30160     Exec-managerial            Wife   White   Female        15024   

       capitalloss  hoursperweek          native  Salary  
0                0            40   United-States   <=50K  
1                0            13   United-States   <=50K  
2                0            40   United-States   <=50K  
3                0            40   United-States   <=50K  
4                0            40            Cuba   <=50K  
...            ...           ...             ...     ...  
30156            0            38   United-States   <=50K  
30157            0            40   United-States    >50K  
30158            0            40   United-States   <=50K  
30159            0            20   United-States   <=50K  
30160            0            40   United-States    >50K  

[30161 rows x 14 columns]

 Performing EDA

In [18]:
pip install pandas-profiling

Note: you may need to restart the kernel to use updated packages.


In [19]:
from pandas_profiling import ProfileReport

In [20]:
profile=ProfileReport(df,title='profile report of the data',explorative=True)

In [21]:
df=df.drop_duplicates()
df

age          workclass      education  educationno  \
0       39          State-gov      Bachelors           13   
1       50   Self-emp-not-inc      Bachelors           13   
2       38            Private        HS-grad            9   
3       53            Private           11th            7   
4       28            Private      Bachelors           13   
...    ...                ...            ...          ...   
30154   53            Private        Masters           14   
30155   22            Private   Some-college           10   
30156   27            Private     Assoc-acdm           12   
30158   58            Private        HS-grad            9   
30160   52       Self-emp-inc        HS-grad            9   

             maritalstatus          occupation    relationship    race  \
0            Never-married        Adm-clerical   Not-in-family   White   
1       Married-civ-spouse     Exec-managerial         Husband   White   
2                 Divorced   Handlers-cleaners   Not-in-family   White   
3       Married-civ-spouse   Handlers-cleaners         Husband   Black   
4       Married-civ-spouse      Prof-specialty            Wife   Black   
...                    ...                 ...             ...     ...   
30154   Married-civ-spouse     Exec-managerial         Husband   White   
30155        Never-married     Protective-serv   Not-in-family   White   
30156   Married-civ-spouse        Tech-support            Wife   White   
30158              Widowed        Adm-clerical       Unmarried   White   
30160   Married-civ-spouse     Exec-managerial            Wife   White   

           sex  capitalgain  capitalloss  hoursperweek          native  Salary  
0         Male         2174            0            40   United-States   <=50K  
1         Male            0            0            13   United-States   <=50K  
2         Male            0            0            40   United-States   <=50K  
3         Male            0            0            40   United-States   <=50K  
4       Female            0            0            40            Cuba   <=50K  
...        ...          ...          ...           ...             ...     ...  
30154     Male            0            0            40   United-States    >50K  
30155     Male            0            0            40   United-States   <=50K  
30156   Female            0            0            38   United-States   <=50K  
30158   Female            0            0            40   United-States   <=50K  
30160   Female        15024            0            40   United-States    >50K  

[26903 rows x 14 columns]

In [26]:
a=df.duplicated()
a

0        False
1        False
2        False
3        False
4        False
         ...  
30154     True
30155     True
30156     True
30158     True
30160    False
Length: 26903, dtype: bool

In [27]:
dummies = pd.get_dummies(df['maritalstatus']).rename(columns=lambda x: 'maritalstatus_' + str(x))

In [28]:
df = pd.concat([df, dummies], axis=1)

In [29]:
df=df.drop('maritalstatus',1)
df

C:\Users\LENOVO\AppData\Local\Temp/ipykernel_1052/3844239688.py:1: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only
  df=df.drop('maritalstatus',1)


age  educationno      sex          native  Salary  \
0       39           13     Male   United-States   <=50K   
1       50           13     Male   United-States   <=50K   
2       38            9     Male   United-States   <=50K   
3       53            7     Male   United-States   <=50K   
4       28           13   Female            Cuba   <=50K   
...    ...          ...      ...             ...     ...   
30154   53           14     Male   United-States    >50K   
30155   22           10     Male   United-States   <=50K   
30156   27           12   Female   United-States   <=50K   
30158   58            9   Female   United-States   <=50K   
30160   52            9   Female   United-States    >50K   

       maritalstatus_ Divorced  maritalstatus_ Married-AF-spouse  \
0                            0                                 0   
1                            0                                 0   
2                            1                                 0   
3                            0                                 0   
4                            0                                 0   
...                        ...                               ...   
30154                        0                                 0   
30155                        0                                 0   
30156                        0                                 0   
30158                        0                                 0   
30160                        0                                 0   

       maritalstatus_ Married-civ-spouse  \
0                                      0   
1                                      1   
2                                      0   
3                                      1   
4                                      1   
...                                  ...   
30154                                  1   
30155                                  0   
30156                                  1   
30158                                  0   
30160                                  1   

       maritalstatus_ Married-spouse-absent  maritalstatus_ Never-married  \
0                                         0                             1   
1                                         0                             0   
2                                         0                             0   
3                                         0                             0   
4                                         0                             0   
...                                     ...                           ...   
30154                                     0                             0   
30155                                     0                             1   
30156                                     0                             0   
30158                                     0                             0   
30160                                     0                             0   

       maritalstatus_ Separated  maritalstatus_ Widowed  
0                             0                       0  
1                             0                       0  
2                             0                       0  
3                             0                       0  
4                             0                       0  
...                         ...                     ...  
30154                         0                       0  
30155                         0                       0  
30156                         0                       0  
30158                         0                       1  
30160                         0                       0  

[26903 rows x 12 columns]

In [30]:
dummies = pd.get_dummies(df['sex']).rename(columns=lambda x: 'sex_' + str(x))
df = pd.concat([df, dummies], axis=1)
df=df.drop('sex',1)
df

C:\Users\LENOVO\AppData\Local\Temp/ipykernel_1052/278336799.py:3: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only
  df=df.drop('sex',1)


age  educationno          native  Salary  maritalstatus_ Divorced  \
0       39           13   United-States   <=50K                        0   
1       50           13   United-States   <=50K                        0   
2       38            9   United-States   <=50K                        1   
3       53            7   United-States   <=50K                        0   
4       28           13            Cuba   <=50K                        0   
...    ...          ...             ...     ...                      ...   
30154   53           14   United-States    >50K                        0   
30155   22           10   United-States   <=50K                        0   
30156   27           12   United-States   <=50K                        0   
30158   58            9   United-States   <=50K                        0   
30160   52            9   United-States    >50K                        0   

       maritalstatus_ Married-AF-spouse  maritalstatus_ Married-civ-spouse  \
0                                     0                                  0   
1                                     0                                  1   
2                                     0                                  0   
3                                     0                                  1   
4                                     0                                  1   
...                                 ...                                ...   
30154                                 0                                  1   
30155                                 0                                  0   
30156                                 0                                  1   
30158                                 0                                  0   
30160                                 0                                  1   

       maritalstatus_ Married-spouse-absent  maritalstatus_ Never-married  \
0                                         0                             1   
1                                         0                             0   
2                                         0                             0   
3                                         0                             0   
4                                         0                             0   
...                                     ...                           ...   
30154                                     0                             0   
30155                                     0                             1   
30156                                     0                             0   
30158                                     0                             0   
30160                                     0                             0   

       maritalstatus_ Separated  maritalstatus_ Widowed  sex_ Female  \
0                             0                       0            0   
1                             0                       0            0   
2                             0                       0            0   
3                             0                       0            0   
4                             0                       0            1   
...                         ...                     ...          ...   
30154                         0                       0            0   
30155                         0                       0            0   
30156                         0                       0            1   
30158                         0                       1            1   
30160                         0                       0            1   

       sex_ Male  
0              1  
1              1  
2              1  
3              1  
4              0  
...          ...  
30154          1  
30155          1  
30156          0  
30158          0  
30160          0  

[26903 rows x 13 columns]

In [31]:
df=df.drop('native',1)
df

C:\Users\LENOVO\AppData\Local\Temp/ipykernel_1052/148304546.py:1: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only
  df=df.drop('native',1)


age  educationno  Salary  maritalstatus_ Divorced  \
0       39           13   <=50K                        0   
1       50           13   <=50K                        0   
2       38            9   <=50K                        1   
3       53            7   <=50K                        0   
4       28           13   <=50K                        0   
...    ...          ...     ...                      ...   
30154   53           14    >50K                        0   
30155   22           10   <=50K                        0   
30156   27           12   <=50K                        0   
30158   58            9   <=50K                        0   
30160   52            9    >50K                        0   

       maritalstatus_ Married-AF-spouse  maritalstatus_ Married-civ-spouse  \
0                                     0                                  0   
1                                     0                                  1   
2                                     0                                  0   
3                                     0                                  1   
4                                     0                                  1   
...                                 ...                                ...   
30154                                 0                                  1   
30155                                 0                                  0   
30156                                 0                                  1   
30158                                 0                                  0   
30160                                 0                                  1   

       maritalstatus_ Married-spouse-absent  maritalstatus_ Never-married  \
0                                         0                             1   
1                                         0                             0   
2                                         0                             0   
3                                         0                             0   
4                                         0                             0   
...                                     ...                           ...   
30154                                     0                             0   
30155                                     0                             1   
30156                                     0                             0   
30158                                     0                             0   
30160                                     0                             0   

       maritalstatus_ Separated  maritalstatus_ Widowed  sex_ Female  \
0                             0                       0            0   
1                             0                       0            0   
2                             0                       0            0   
3                             0                       0            0   
4                             0                       0            1   
...                         ...                     ...          ...   
30154                         0                       0            0   
30155                         0                       0            0   
30156                         0                       0            1   
30158                         0                       1            1   
30160                         0                       0            1   

       sex_ Male  
0              1  
1              1  
2              1  
3              1  
4              0  
...          ...  
30154          1  
30155          1  
30156          0  
30158          0  
30160          0  

[26903 rows x 12 columns]

In [32]:
predictors=df.drop(['Salary'],axis=1)
predictors

age  educationno  maritalstatus_ Divorced  \
0       39           13                        0   
1       50           13                        0   
2       38            9                        1   
3       53            7                        0   
4       28           13                        0   
...    ...          ...                      ...   
30154   53           14                        0   
30155   22           10                        0   
30156   27           12                        0   
30158   58            9                        0   
30160   52            9                        0   

       maritalstatus_ Married-AF-spouse  maritalstatus_ Married-civ-spouse  \
0                                     0                                  0   
1                                     0                                  1   
2                                     0                                  0   
3                                     0                                  1   
4                                     0                                  1   
...                                 ...                                ...   
30154                                 0                                  1   
30155                                 0                                  0   
30156                                 0                                  1   
30158                                 0                                  0   
30160                                 0                                  1   

       maritalstatus_ Married-spouse-absent  maritalstatus_ Never-married  \
0                                         0                             1   
1                                         0                             0   
2                                         0                             0   
3                                         0                             0   
4                                         0                             0   
...                                     ...                           ...   
30154                                     0                             0   
30155                                     0                             1   
30156                                     0                             0   
30158                                     0                             0   
30160                                     0                             0   

       maritalstatus_ Separated  maritalstatus_ Widowed  sex_ Female  \
0                             0                       0            0   
1                             0                       0            0   
2                             0                       0            0   
3                             0                       0            0   
4                             0                       0            1   
...                         ...                     ...          ...   
30154                         0                       0            0   
30155                         0                       0            0   
30156                         0                       0            1   
30158                         0                       1            1   
30160                         0                       0            1   

       sex_ Male  
0              1  
1              1  
2              1  
3              1  
4              0  
...          ...  
30154          1  
30155          1  
30156          0  
30158          0  
30160          0  

[26903 rows x 11 columns]

In [33]:
ip_columns = ['age','educationno','sex_ Female','sex_ Male','maritalstatus_ Divorced','maritalstatus_ Married-AF-spouse','maritalstatus_ Married-civ-spouse','maritalstatus_ Married-spouse-absent','maritalstatus_ Never-married','maritalstatus_ Separated','maritalstatus_ Widowed']
op_column = ['Salary']

In [34]:
Xtrain,Xtest,ytrain,ytest = train_test_split(df[ip_columns],df[op_column],test_size=0.3, random_state=0)

In [35]:
ignb = GaussianNB()
imnb = MultinomialNB()

In [36]:
pred_gnb = ignb.fit(Xtrain,ytrain).predict(Xtest)
pred_mnb = imnb.fit(Xtrain,ytrain).predict(Xtest)

C:\Users\LENOVO\anaconda3\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\LENOVO\anaconda3\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


Confusion matrix GaussianNB model

In [37]:
confusion_matrix(ytest,pred_gnb)

array([[4199, 1831],
       [ 420, 1621]], dtype=int64)

In [38]:
confusion_matrix(ytest,pred_gnb)

array([[4199, 1831],
       [ 420, 1621]], dtype=int64)

In [39]:
np.mean(pred_gnb==ytest.values.flatten())

0.7211002354107298

 Confusion matrix multinomialNB model

In [40]:
confusion_matrix(ytest,pred_mnb)

array([[4237, 1793],
       [ 536, 1505]], dtype=int64)

In [41]:
pd.crosstab(ytest.values.flatten(),pred_mnb)

col_0    <=50K   >50K
row_0                
 <=50K    4237   1793
 >50K      536   1505

In [42]:
np.mean(pred_mnb==ytest.values.flatten()) 

0.7114360054516169

In [43]:
confusion_matrix(ytest,pred_mnb)

array([[4237, 1793],
       [ 536, 1505]], dtype=int64)

In [44]:
confusion_matrix(ytest,pred_gnb)

array([[4199, 1831],
       [ 420, 1621]], dtype=int64)